### ISSUE TITLE
create k3s HA cluster failed

### ISSUE THREAD

**Issue by tboevil** [innobead/kubefire#84]
**Describe the bug**
When creating the second node via k3s, use server `--node-name`  instead of `--server`，Otherwise it will prompt `Job for k3s-agent.service failed because the service did not take the steps required by its unit configuration.`，attach that virtual machine and you can see ` Incorrect Usage: flag needs an argument: -server`

related code: https://github.com/innobead/kubefire/blob/main/pkg/bootstrap/k3s.go#L201
```
**To Reproduce**
config:
```yaml
name: "kubefire-dev"
bootstrapper: k3s
pubkey: ""
prikey: ""
version: ""
image: ghcr.io/innobead/kubefire-opensuse-leap:15.2
kernel_image: ghcr.io/innobead/kubefire-ignite-kernel:4.19.125-amd64
kernel_args: console=ttyS0 reboot=k panic=1 pci=off ip=dhcp security=apparmor apparmor=1
extra_options: {}
deployed: false
master:
  count: 3
  memory: 2GB
  cpus: 2
  disk_size: 10GB
worker:
  count: 3
  memory: 2GB
  cpus: 2
  disk_size: 10GB
```

kubefire cluster create dev -c dev.conf -l debug

**Expected behavior**
Successfully created k3s cluster

**Environment**
```bash
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ kubefire version
Version: v0.3.10
Build: 35cb33b-20230416001838
$ kubefire info
CONTAINERD	IGNITE 	CNI   	RUNC 	CNIPLUGIN
v1.6.20   	v0.10.0	v1.1.1	1.1.6	0.4.0/kubefire-cni-bridge
```

**Additional context**
I'm happy to provide MR if help is needed, but I'm not found Contributing docs
